"""gacha record

迁移 ID: dc0df0f1535b
父迁移:
创建时间: 2025-08-07 18:07:55.735446

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dc0df0f1535b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("gacha",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skland_gacha_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=False, comment="关联的用户ID"),
        sa.Column("char_uid", sa.VARCHAR(), nullable=False, comment="关联的角色UID"),
        sa.Column("pool_id", sa.Text(), nullable=False),
        sa.Column("pool_name", sa.Text(), nullable=False),
        sa.Column("char_id", sa.Text(), nullable=False),
        sa.Column("char_name", sa.Text(), nullable=False),
        sa.Column("rarity", sa.Integer(), nullable=False),
        sa.Column("is_new", sa.Boolean(), nullable=False),
        sa.Column("gacha_ts", sa.BigInteger(), nullable=False, comment="Gacha Timestamp"),
        sa.Column("pos", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["char_uid"], ["skland_characters.uid"], name=op.f("fk_skland_gacha_record_char_uid_skland_characters")
        ),
        sa.ForeignKeyConstraint(["uid"], ["skland_user.id"], name=op.f("fk_skland_gacha_record_uid_skland_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skland_gacha_record")),
        sa.UniqueConstraint("char_id", "gacha_ts", "pos", name="_character_ts_pos_uc"),
        info={"bind_key": "nonebot_plugin_skland"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skland_gacha_record")
    # ### end Alembic commands ###
